language: cpp
dist: xenial
sudo: required

os:
  - linux

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get install -y --allow-unauthenticated git gcc g++ gobjc llvm-dev cmake

script:
  - cd cctools && ./configure && make
