language: cpp
dist: xenial
sudo: required

os:
  - linux

compiler:
  - gcc
  - clang

before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install -y --allow-unauthenticated git gcc g++ gobjc llvm-dev cmake; fi

script:
  - cd cctools && ./configure && make
